language: cpp

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

install:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install -qq libboost-system-dev libboost-thread-dev libtinyxml-dev
  - sudo apt-get --force-yes install icub
  - sudo apt-get install cmake

before_script:
  - cmake --version
  - cd ..
   #eigen 3.2 support
  - hg clone https://bitbucket.org/eigen/eigen/
  - cd eigen
  - hg checkout 3.2.0
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # Build orocos_kinematics_dynamics and install it in a local directory
  - git clone https://github.com/orocos/orocos_kinematics_dynamics
  - cd orocos_kinematics_dynamics
  - cd orocos_kdl
  - mkdir build
  - cd build
  - mkdir local_install
  - cmake -DCMAKE_INSTALL_PREFIX="./local_install" -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..
  - make
  - make install
  - cd ../../..
  # Build kdl_codyco and install it in a local directory
  - git clone https://github.com/traversaro/kdl_codyco
  - cd kdl_codyco
  - mkdir build
  - cd build
  - mkdir local_install
  - cmake -DCMAKE_INSTALL_PREFIX="./local_install" -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..
  - make
  - make install
  - cd ../..
  # Build kdl_format_io and install it in a local directory
  - sudo chmod +x ./codyco-commons/.travis/build_urdfdom
  - ./codyco-commons/.travis/build_urdfdom
  - git clone https://github.com/traversaro/kdl_format_io
  - cd kdl_format_io
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..
  - make
  - sudo make install
  - cd ../..
  # Build and install YCM
  - git clone https://github.com/robotology/ycm.git
  - cd ycm
  - mkdir build
  - cd build 
  - cmake ..
  - make 
  - sudo make install
  - cd ../..
  # Prepare iDynTree build
  - git clone https://github.com/robotology-playground/iDynTree
  - cd iDynTree
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DIDYNTREE_BUILD_TESTS:BOOL=ON ..
  - make
  - sudo make install
  - ctest -V
  - cd ../..
  
script:
  - cd iDynTreeTests
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..
  - make

notifications:
  email:
    - pegua1@gmail.com
